### PR TITLE
Convert test to use describe.each()

### PR DESCRIPTION
**Pull request by whscullin**
The way we name tests using template strings breaks VSCode's inline test debugging, if we want it to work again we need to switch to naming scheme that uses describe blocks for variable names so that test names are static. 

Here's expr.spec.ts converted to do that. If this seems reasonable we can switch other tests, as well.

### CODE REVIEW

**Comment by christopherswenson** [comment]
This looks good to me. I can try it out tomorrow.

**Comment by mtoy-googly-moogly** [comment]
actually no ... stop ... let me look

**Comment by mtoy-googly-moogly** [comment]
Yeah I want to talk about this ... I'm not in love with how we run tests across databases, but I think this is worse.

**Review by mtoy-googly-moogly — APPROVED** [review]
OK, I've merged main into this PR, changed the thing I did in main to do it the way @whscullin does it here. This is ready to go.

Apologies again for not reading this the first time and just having a canned reaction to the word "testing".

**Pull request merged**
